name: Trigger auto deployment for my-spring-music

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/my-spring-music-AutoDeployTrigger-7343afdc-93c1-4fbb-b47e-ba885964ecd3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYSPRINGMUSIC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYSPRINGMUSIC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYSPRINGMUSIC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.MYSPRINGMUSIC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYSPRINGMUSIC_REGISTRY_PASSWORD }}
          containerAppName: my-spring-music
          resourceGroup: rg-aca
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


